<a href="https://colab.research.google.com/github/Guympele/Projets-on-Data-Analysis/blob/Data-sets-analysis/Project_3_US_Arrests_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget https://www.dropbox.com/s/5kobpxrkzlj2ek6/STAT%20S01V19.zip
!unzip "STAT S01V19.zip"

--2024-04-09 08:18:50--  https://www.dropbox.com/s/5kobpxrkzlj2ek6/STAT%20S01V19.zip
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/5kobpxrkzlj2ek6/STAT%20S01V19.zip [following]
--2024-04-09 08:18:51--  https://www.dropbox.com/s/raw/5kobpxrkzlj2ek6/STAT%20S01V19.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucff15b08fe5c4bb19f1604af627.dl.dropboxusercontent.com/cd/0/inline/CQpyvxDoOZJPLCA1VIgq-_JJ40sVhaLA4BcpywrMCDVuOIq9AXdB7LvZo1n976lt7EGEwMrT2Svn4QMf8OHg5clllpgA_YWoViUi4ybJyou2kWJ3NthSwCpiiwbP2QV3bZQYyb-vFpgSO3H3eo61YE1t/file# [following]
--2024-04-09 08:18:51--  https://ucff15b08fe5c4bb19f1604af627.dl.dropboxusercontent.com/cd/0/inline/CQpyvxDoOZJPLCA1VIgq-_JJ40sVhaLA4BcpywrMCDVuOIq9AXdB7LvZo1n976lt7EGEwMrT2Svn4QMf8OHg5cl

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_excel("USArrests.xlsx")
df.head()

Unnamed: 0  Murder  Assault  UrbanPop  Fraud
0     Alabama    13.2      236        58   21.2
1      Alaska    10.0      263        48   44.5
2     Arizona     8.1      294        80   31.0
3    Arkansas     8.8      190        50   19.5
4  California     9.0      276        91   40.6

**Task** **1** : Let analyse the Measures of spread and Shape ( the IQR, Kurtosis,and Skewness ) on Assault & Fraud columns.

In [27]:
from scipy.stats import iqr, kurtosis,skew

# IQR on Assault and Fraud data
iqr(df[['Assault','Fraud']], axis=0)

array([140. ,  11.1])

In [28]:
# Skewness on Assaut and Fraud data
skew(df[['Assault','Fraud']], axis=0)

array([0.22731787, 0.77696132])

In [30]:
# Kurtosis for Assault and Fraud data
print(f"The Pearson Kurtosis of Points Column is:{kurtosis(df[['Assault', 'Fraud']], fisher=False,axis=0)}")
print(f"The Fisher's kurtosis of Points Column is:{kurtosis(df[['Assault','Fraud']], fisher=True, axis=0)}")

The Pearson Kurtosis of Points Column is:[1.93097995 3.20189779]
The Fisher's kurtosis of Points Column is:[-1.06902005  0.20189779]


**Task** **2** : Let evaluate the Z-Score based on data in the Assault column

In [15]:
from scipy.stats import zscore

z = np.abs(zscore(df['Assault']))
z

0     0.790787
1     1.118060
2     1.493817
3     0.233212
4     1.275635
5     0.402909
6     0.736484
7     0.815030
8     1.990786
9     0.487757
10    1.512241
11    0.615272
12    0.948363
13    0.700121
14    1.391029
15    0.675878
16    0.748605
17    0.948363
18    1.063757
19    1.566544
20    0.263757
21    1.021090
22    1.197090
23    1.069575
24    0.087757
25    0.748605
26    0.833454
27    0.984726
28    1.378908
29    0.142545
30    1.384726
31    1.008969
32    2.015028
33    1.524362
34    0.615272
35    0.239515
36    0.142545
37    0.784969
38    0.039273
39    1.311999
40    1.027393
41    0.208970
42    0.366545
43    0.615272
44    1.487999
45    0.178909
46    0.312242
47    1.087999
48    1.427393
49    0.118303
Name: Assault, dtype: float64

**Task** **3** : Let detect Outliers based on data in URBANPOP using Z-score

In [17]:
u =np.abs(zscore(df['UrbanPop']))
u

0     0.144561
1     0.146947
2     0.139311
3     0.146470
4     0.136687
5     0.139788
6     0.140027
7     0.141220
8     0.139311
9     0.144083
10    0.138595
11    0.145515
12    0.138595
13    0.142890
14    0.144799
15    0.142652
16    0.145992
17    0.142652
18    0.146231
19    0.142413
20    6.999961
21    0.140743
22    0.142652
23    0.147901
24    0.141697
25    0.145754
26    0.143606
27    0.139073
28    0.145038
29    0.137164
30    0.141697
31    0.137880
32    0.147663
33    0.147901
34    0.140504
35    0.142175
36    0.142413
37    0.141220
38    0.137641
39    0.146947
40    0.147663
41    0.144322
42    0.139311
43    0.139311
44    0.150765
45    0.143368
46    0.140982
47    0.149094
48    0.142652
49    0.144083
Name: UrbanPop, dtype: float64

In [18]:
np.where(u>2)

(array([20]),)

In [37]:
df.iloc[20]

Unnamed: 0    Massachusetts
Murder                  4.4
Assault                 149
UrbanPop              30000
Fraud                  16.3
Name: 20, dtype: object

We have only have 1 outlier on UrbanPop data in the state of Massachusetts.

**Task** **4** : Let evaluate Outlier based on urbanpop column using IQR

In [34]:
# Function to detect Outliers by using the IQR
def detect_outliers(column):
    # Calculate the first and third quartile
    Q1 = np.quantile(df[column], 0.25)
    Q3 = np.quantile(df[column], 0.75)

    # Calculate the IQR (Interquartile Range)
    IQR = Q3 - Q1

    # Define the bounds to detect outliers.
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Find the indices of outliers
    return df[(df[column] < lower_bound) | (df[column] > upper_bound)]


In [36]:
# Application
detect_outliers('UrbanPop')

Unnamed: 0  Murder  Assault  UrbanPop  Fraud
20  Massachusetts     4.4      149     30000   16.3

We found again only one outlier on Urbanpop data on Massachusetts State as we found by using zscore method.

**Task** **5** : Let calculate the Range,Standard Deviation, and Variance of data in Urbanpop and Assault

In [21]:
# Range on urbanpop and assault data
min_value = df[['UrbanPop','Assault']].min()
max_value = df[['UrbanPop','Assault']].max()

range_value = max_value - min_value
print(range_value)

UrbanPop    29968
Assault       292
dtype: int64


In [40]:
# To evaluate the range we could also do
print(np.ptp(df[['Assault','UrbanPop']],axis=0))

Assault       292
UrbanPop    29968
dtype: int64


In [23]:
# Standard deviation on Urbanpop and Assault data
df[['UrbanPop','Assault']].std(ddof=0)

UrbanPop    4190.903575
Assault       82.500075
dtype: float64

In [24]:
# Variance on Urbanpop and Assault data
df[['UrbanPop','Assault']].var(ddof=0)

UrbanPop    1.756367e+07
Assault     6.806262e+03
dtype: float64